### ISSUE TITLE
React 17+ support

### ISSUE THREAD

**Issue by hnqlv** [bamlab/react-native-flipper-performance-monitor#69]
Bonjour @Almouro, do you have any plans to support React 17 and 18? Merci

**Comment by Almouro** [comment]
Bom dia @hnqlv! 

So far, the plugin is reporting FPS exclusively from the native side, so it supports RN apps with React 17 or React 18
Or do you mean support for web apps?

**Comment by hnqlv** [comment]
@Almouro yea sorry, talking specifically about `react-native-startup-trace` package:

```json
"peerDependencies": {
  "react": "^16.8.1"
}
```

**Comment by Almouro** [comment]
Oh right, should probably move that one into it's own repo 😅
It should be compatible with both React 17 and React 18 for sure, I'll update the peer dependencies

**Comment by hnqlv** [comment]
@Almouro great! I wanted to make sure before forcing the peer deps! 😆 Appreciate the fast response, cheers!
