### ISSUE TITLE
Example app not connecting with Flipper

### ISSUE THREAD

**Issue by mohit23x** [bamlab/react-native-flipper-performance-monitor#70]
Tried running the example app but it is not able to connect with the installed flipper plugin.

Flipper version: `0.157.0`

Also, got this warning in flipper logs
<img width="771" alt="image" src="https://user-images.githubusercontent.com/36567063/183590598-00296757-c709-4e47-b808-c4e5cc2285ad.png">

Screenshot:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/36567063/183590747-e7154ce3-f2b9-4c7a-a956-7b213ab88040.png">

**Comment by Almouro** [comment]
Hi @mohit23x !

It seems you have the wrong Flipper plugin installed 
It seems you have https://www.npmjs.com/package/flipper-plugin-react-native-performance installed which is the old Flipper plugin for [the original react-native-performance](https://github.com/oblador/react-native-performance/blob/master/packages/flipper-plugin-performance/README.md). It's great to measure some timings, app start and I personally use it as well!

However, ours should be named `rn-perf-monitor` in the Flipper marketplace (https://github.com/bamlab/react-native-flipper-performance-monitor#flipper)

**Comment by mohit23x** [comment]
Got it, thanks @Almouro for the quick response.
