### ISSUE TITLE
reactContext is null inside FPSMonitor Class

### ISSUE THREAD

**Issue by whoami-shubham** [bamlab/react-native-flipper-performance-monitor#71]
Thanks for creating this library, 
It works well with apps created using React Native,
However, I was trying to use it for the brownfield react native App.
I have manually linked this library but when I click on "Start Measuring " it crashes with a null pointer Exception, then I logged some variables and I found reactContext was null. 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/28999685/190322799-6f99a176-65d6-4a33-a501-224a7bfe27f3.png">

I also tried after moving line 51 to 36 in the following file, I got the same result
my `ReactNativeFlipper.kt` File

<img width="945" alt="image" src="https://user-images.githubusercontent.com/28999685/190323143-66ee25ac-d280-4df1-af2a-b1964e500c31.png">

```json
  "react": "17.0.2",
 "react-native": "0.66.3",
 "react-native-flipper-performance-plugin": "^0.3.1"
```
```
compileSdkVersion = 31
 targetSdkVersion = 31
 minSdkVersion = 21
 flipper Version 0.136.0
 
```

**Comment by Almouro** [comment]
Hi @whoami-shubham, thanks for this issue!

Nice debugging skills! 💪
I haven't worked with a brownfield app in a while (and this plugin has indeed not been tested by us on a brownfield app). 
I'm pretty sure your second attempt is the correct way to deal with this, but this might have been broken in the `0.3.0` update for expo support.

Could you retry with version `0.2.1` of the native plugin?

(Also for Android performance, you can give https://github.com/bamlab/android-performance-profiler a go if you feel like it. It requires no installation and support the native side as well. FPS reporting might be a bit wonky but is being fixed soon 🤞)

**Comment by whoami-shubham** [comment]
Thanks, I will try with version `0.2.1`
