### ISSUE TITLE
Unknown type name 'FlipperClient' Use of undeclared identifier 'FlipperClient' error

### ISSUE THREAD

**Issue by hadnet** [bamlab/react-native-flipper-performance-monitor#73]
Why I'm getting this error? I'm using RN 0.70.1
![Screen Shot 2022-10-05 at 2 02 10 AM](https://user-images.githubusercontent.com/13828833/193984942-70099142-9d94-4522-b8cb-e77e4720f44c.png)

**Comment by Almouro** [comment]
Hi @hadnet,
I've upgraded the example app to 0.70.3 https://github.com/bamlab/react-native-flipper-performance-monitor/pull/74 but didn't run into any issue. Does it build for you?

It would seem Flipper isn't installed properly somehow, do you have Flipper properly enabled in your `Podfile`?

Also do other native iOS Flipper plugins like Layout and Shared preferences show up in Flipper for you?
<img width="226" alt="image" src="https://user-images.githubusercontent.com/4534323/195446132-a79a86ff-b6f4-461d-93dd-3a78defc9c82.png">

**Comment by hadnet** [comment]
Sorry for the delay, the error was the location of the #ifdef FB_SONARKIT_ENABLED block, happens that it needs to be strictly before @implementation AppDelegate. Thanks anyway.
